define( [ "qlik", "jquery", "util", "./enigma", "autogenerated/qix/engine-api", "text!./leonardo/leonardo-ui.min.css", "text!./style.css", "./jquery-ui-1.12.1.custom/jquery-ui.min", "text!./jquery-ui-1.12.1.custom/jquery-ui.min.css"],
function ( qlik, $, Util, enigma, schema, leoCSS, myCSS, jqueryUI, jqueryUICSS) {
	$("<style>").html(leoCSS).appendTo("head");
	$("<style>").html(myCSS).appendTo("head");
	$("<style>").html(jqueryUICSS).appendTo("head");

	return {
		support : {
			snapshot: false,
			export: false,
			exportData : false
		},
		paint: function ($element) {
      		var self = this;
			var html;
			var buttonSelections;
			buttonSelections = "<div class='lui-text-default' id='grouperTextSel'>Create a new master item to group currently selected values from a single field.<BR>";
			buttonSelections += "<button class='lui-button' id='addSelDim'>";
			buttonSelections += "<span class='lui-button__icon  lui-icon  lui-icon--plus'></span><span class='lui-button__text'>add master dimension</span>";
			buttonSelections += "</button></div>";
			buttonSelections += "<div class='lui-text-default' id='grouperTextNew'>Create a new master item to group values from a single field.<BR>";
			buttonSelections += "<button class='lui-button' id='addNewDim'>";
			buttonSelections += "<span class='lui-button__icon  lui-icon  lui-icon--plus'></span><span class='lui-button__text'>add master dimension</span>";
			buttonSelections += "</button></div>";
			buttonSelections += "<div class='lui-text-default' id='grouperTextBin'>Create a new master item to group values into bins.<BR>";
			buttonSelections += "<button class='lui-button' id='addNewBin'>";
			buttonSelections += "<span class='lui-button__icon  lui-icon  lui-icon--plus'></span><span class='lui-button__text'>add master dimension</span>";
			buttonSelections += "</button></div>";
			// buttonSelections += "<div class='lui-text-default' id='grouperTextMsr'>Create a new master item to group numerical values by an expression. </div>";
			// buttonSelections += "<button class='lui-button' id='addMsr'>";
			// buttonSelections += "<span class='lui-button__icon  lui-icon  lui-icon--plus'></span><span class='lui-button__text'>add master measure</span>";
			// buttonSelections += "</button>";
			html = buttonSelections;

			$element.html( html );
			
			// Enigma v2
			var secure = !Util.isSecure ? 'ws' : 'wss';
			var urlConfig = {
				host: Util.hostname,
				port: Util.port || undefined,
				appId: encodeURIComponent(String.raw`C:\Users\tmg\Documents\Qlik\Sense\Apps\GrouperTest.qvf`),
				secure: secure
			}
			var cfg = {
				schema, 
				url: urlConfig.secure + '://' + urlConfig.host + ':' + urlConfig.port + '/app/' + urlConfig.appId,
				appId: 'GrouperTest.qvf'
			};
			// console.log('config',cfg);

			$("#addSelDim").click(function(){
				console.log("add master dimension group based on selections");
		    	var selections = [];
				const session = enigma.create(cfg);
				session.open().then((global) => {
					global.getActiveDoc().then((doc) => {
						console.log("Connected to QIX");
						doc.createSessionObject({
							"qInfo": {
								"qId": "",
								"qType": "SessionLists"
							},
							"qSelectionObjectDef": {}
						})
						.then((sessionObject) => sessionObject.getLayout())
					    .then((layout) => {
					    	console.log(JSON.stringify(layout.qSelectionObject.qSelections, null, '  '))
					    	for(i=0; i<layout.qSelectionObject.qSelections.length; i++){
					    		sField = {};
					    		sField['name'] = layout.qSelectionObject.qSelections[i].qField;
					    		sField['vals'] = [];
					    		for(j=0; j<layout.qSelectionObject.qSelections[i].qSelectedFieldSelectionInfo.length; j++){
					    			sField['vals'].push(layout.qSelectionObject.qSelections[i].qSelectedFieldSelectionInfo[j].qName);
					    		}
					    		selections.push(sField);
					    	}
					    	console.log("selections",selections);
					    })
						.then(() => {
							console.log("Current Selections for dimension", selections);
							
							if(selections.length != 1){
								return Promise.reject("Please have exactly one field with selections");
							}

							var dimDef = {
						      "qInfo": {
						        "qType": "dimension"
						      },
						      "qDim": {
						        "title": "",
						        "qGrouping": "N",
						        "qFieldDefs": [],
						        "qFieldLabels": []
						      },
						      "qMetaDef": {
						        "title": "",
						        "description": "",
						        "tags": []
						      }
						    };
					    	var ifStmt = "=";
					    	var dimFields = "";
					    	var ctr = 0;
						    for(i=0; i<1;i++){
						    	dimFields += selections[i].name + ",";
							    for(j=0; j<selections[i].vals.length;j++){
							    	ifStmt += "if(\"" + selections[i].name + "\" = '" + selections[i].vals[j] + "', '" + selections[i].vals[j] + "'";
							    	if(j<selections[i].vals.length-1){
							    		ifStmt += ",\n";
							    	}
							    	ctr++;
							    }
							}
						    for(k=0; k<ctr; k++)
						    	ifStmt += ")";
							dimFields = dimFields.substring(0, dimFields.length-1); // remove last comma

					    	dimDef.qDim.qFieldDefs.push(ifStmt);
					    	dimDef.qDim.qFieldLabels.push("Filtered " + dimFields);
					    	dimDef.qDim.title = "Filtered " + dimFields;
					    	dimDef.qMetaDef.title = "Filtered " + dimFields;

					    	console.log("dimDef",dimDef);

							doc.createDimension(dimDef)
						    .then(result => {
						    	console.log(result);
						    	if(result.delta){
						    		$("#grouperTextSel").children().slice(2).remove();

									var msg = "Your new master dimension has been added";
									var toast = "<div class='lui-toast' id='grouperToast'><span>" + msg + "</span></div>"
									$("#grouperTextSel").append(toast);
									$("#grouperToast").fadeOut(4000);
									setTimeout(function(){$("#grouperToast").remove();},4000);
						    	}
						    });
						    // .then(doc.createSessionObject({
						    // 	"qInfo": {
						    // 		"qId": "mySessionObject",
						    // 		"qType": "DimensionList"
						    // 	},
						    // 	"qDimensionListDef": {
							   //      "qType": "Dimension",
							   //      "qData": {
										// "title": "/title",
										// "tags": "/tags",
										// "grouping": "/qDim/qGrouping",
										// "info": "/qDimInfos"
							   //      }
							   //  }
						    // }))
						    // .then(sessionObj => sessionObj.getLayout())
						    // .then(layout => console.log(JSON.stringify(layout, null, '  ')))
						})
						.then(function(error){ 
							// not called 
						}, function(error){
							console.log(error);
							var toast = "<div class='lui-toast' id='grouperToast'><span>" + error + "</span></div>"
							$("#grouperTextSel").append(toast);
							$("#grouperToast").fadeOut(4000);
							setTimeout(function(){$("#grouperToast").remove();},4000);
						})
					})
				}).catch(function(err) {
					console.log('Something went wrong', err);
				});
			});

			$("#addNewDim").click(function(){
				console.log("add master dimension group based on new field selection");
		    	var fields = [];
		    	var mListObject;
				const session = enigma.create(cfg);
				session.open().then((global) => {
					global.getActiveDoc().then((doc) => {
						console.log("Connected to QIX");
						doc.createObject({
							qInfo: {
								qType: 'my-field-list',
							},
								qFieldListDef: {},
						})
			          	.then(object => object.getLayout())
			          	.then(layout => {
			          		console.log('Field list:', JSON.stringify(layout, null, '  '));
			          		var list = "<select class='lui-select' id='grouperNewDimField'>";
			          		list += "<option selected disabled>Select the field to filter on</option>";
			          		layout.qFieldList.qItems.forEach( function ( row ) {
			          			list += "<option value='" + row.qName + "'>" + row.qName + "</option>";
			          		});
			          		list += "</select>";
			          		$("#grouperTextNew").append(list);

			          		$("#grouperNewDimField").change(function(){
			          			var val = $("#grouperNewDimField option:selected").val();
			          			console.log('grouper field selected',val);

								doc.createObject({
								  qInfo: {
								    qType: 'my-list-object',
								  },
								  qListObjectDef: {
								    qDef: {
								      qFieldDefs: [val],
								      "qSortCriterias": [
							            {
							              "qSortByState": 1,
							              "qSortByFrequency": 0,
							              "qSortByNumeric": 0,
							              "qSortByAscii": 1,
							              "qSortByLoadOrder": 0,
							              "qSortByExpression": 0,
							              "qExpression": {
							                "qv": ""
							              }
							            }
							          ]
								    },
								    qShowAlternatives: true,
								    qInitialDataFetch: [{
								      qTop: 0,
								      qHeight: 1000,
								      qLeft: 0,
								      qWidth: 1,
								    }],
								  },
								})
								.then((listObject) => {
									mListObject = listObject;
									listObject.getLayout()
									.then((layout) => {
								        console.log('Generic object info:', JSON.stringify(layout.qInfo, null, '  '));
								        console.log('List object state:', JSON.stringify(layout.qListObject.qDimensionInfo.qStateCounts, null, '  '));
								        console.log('List object data:', JSON.stringify(layout.qListObject.qDataPages[0].qMatrix, null, '  '));

						          		var listbox = "<div id='grouperFieldValues' style='overflow: auto'>";
						          		listbox += "<ol id='grouperSelect'>";
										layout.qListObject.qDataPages[0].qMatrix.forEach( function ( row ) {
											listbox += '<li class="data state' + row[0].qState + ' ui-widget-content" data-value="' + row[0].qElemNumber + '">' + row[0].qText;
											listbox += '</li>';
										} );
										listbox += "</ol></div>";
										listbox += "<button class='lui-button' id='createNewDim'>";
										listbox += "<span class='lui-button__icon  lui-icon  lui-icon--plus'></span><span class='lui-button__text'>create master dimension</span>";
										listbox += "</button>";
						          		if($("#grouperFieldValues").length)
						          			$("#grouperFieldValues").replaceWith(listbox);
						          		else
						          			$("#grouperTextNew").append(listbox);

									    $( "#grouperSelect" ).selectable({

									    	unselected: function(e, ui){
									    		console.log(ui.unselected);
									    		$(ui.unselected).children('span').remove();
									    	},
									    	selected: function(e, ui){
									    		if(!$(ui.selected).children("span").length)
									    			$(ui.selected).append("<span class='lui-icon lui-icon--tick'></span>");
									    	}
									    });

									    mListObject.on('changed', () => {
									    	mListObject.getLayout().then(layout => {
									    		console.log("changed mListObject", JSON.stringify(layout, null, '  '));

												layout.qListObject.qDataPages[0].qMatrix.forEach( function ( row ) {
													console.log($("#grouperSelect li").filter(function() { return this.innerHTML === row[0].qText; }));
										    		// $("#grouperSelect li").filter(function() { return this.innerHTML === row[0].qText; })
										    		$("li").filter(function() { return this.innerText === row[0].qText; })
														.removeClass("stateO stateA stateS stateX stateXS")
														.addClass("state"+row[0].qState);
												});
									    	});
									    });

						          		$("#createNewDim").click(function(){
								    		sField = {};
								    		sField['name'] = $("#grouperNewDimField").find(":selected").text();
								    		sField['vals'] = [];
									        $("#grouperSelect .ui-selected").each(function() {
								    			sField['vals'].push($(this).text());
									        });
									        console.log(JSON.stringify(sField, null, '  '));
									        console.log("# sels", sField.vals.length);

											if(sField.vals.length == 0){
												console.log("NO SELECTIONS");
												var error = "Please select at least one value";
												var toast = "<div class='lui-toast' id='grouperToast'><span>" + error + "</span></div>"
												$("#grouperTextNew").append(toast);
												$("#grouperToast").fadeOut(4000);
												setTimeout(function(){$("#grouperToast").remove();},4000);
												return;
											}

											var dimDef = {
										      "qInfo": {
										        "qType": "dimension"
										      },
										      "qDim": {
										        "title": "",
										        "qGrouping": "N",
										        "qFieldDefs": [],
										        "qFieldLabels": []
										      },
										      "qMetaDef": {
										        "title": "",
										        "description": "",
										        "tags": []
										      }
										    };
									    	var ifStmt = "=";
									    	var ctr = 0;
										    for(j=0; j<sField.vals.length;j++){
										    	ifStmt += "if(\"" + sField.name + "\" = '" + sField.vals[j] + "', '" + sField.vals[j] + "'";
										    	if(j<sField.vals.length-1){
										    		ifStmt += ",\n";
										    	}
										    	ctr++;
										    }
										    for(k=0; k<ctr; k++)
										    	ifStmt += ")";

									    	dimDef.qDim.qFieldDefs.push(ifStmt);
									    	dimDef.qDim.qFieldLabels.push("Filtered " + sField.name);
									    	dimDef.qDim.title = "Filtered " + sField.name;
									    	dimDef.qMetaDef.title = "Filtered " + sField.name;

									    	console.log("dimDef",dimDef);

											doc.createDimension(dimDef)
										    .then(result => {
										    	console.log(result);
										    	if(result.delta){
										    		$("#grouperTextNew").children().slice(2).remove();

													var msg = "Your new master dimension has been added";
													var toast = "<div class='lui-toast' id='grouperToast'><span>" + msg + "</span></div>"
													$("#grouperTextNew").append(toast);
													$("#grouperToast").fadeOut(4000);
													setTimeout(function(){$("#grouperToast").remove();},4000);
										    	}
										    });
										    // .then(doc.createSessionObject({
										    // 	"qInfo": {
										    // 		"qId": "mySessionObject",
										    // 		"qType": "DimensionList"
										    // 	},
										    // 	"qDimensionListDef": {
											   //      "qType": "Dimension",
											   //      "qData": {
														// "title": "/title",
														// "tags": "/tags",
														// "grouping": "/qDim/qGrouping",
														// "info": "/qDimInfos"
											   //      }
											   //  }
										    // }))
										    // .then(sessionObj => sessionObj.getLayout())
										    // .then(layout => console.log(JSON.stringify(layout, null, '  ')))

						          		})

								    })
								})
			          		});
			          	})
					})
				}).catch(function(err) {
					console.log('Something went wrong', err);
				});
			});

			$("#addNewBin").click(function(){
				console.log("add master dimension based on bins");
				const session = enigma.create(cfg);
				session.open().then((global) => {
					global.getActiveDoc().then((doc) => {
						console.log("Connected to QIX");
						doc.createObject({
							qInfo: {
								qType: 'my-field-list',
							},
								qFieldListDef: {},
						})
			          	.then(object => object.getLayout())
			          	.then(layout => {
			          		console.log('Field list:', JSON.stringify(layout, null, '  '));
			          		var list = "<select class='lui-select' id='grouperNewBinField'>";
			          		list += "<option selected disabled>Select the field to filter on</option>";
			          		layout.qFieldList.qItems.forEach( function ( row ) {
			          			list += "<option value='" + row.qName + "'>" + row.qName + "</option>";
			          		});
			          		list += "</select>";
			          		$("#grouperTextBin").append(list);

			          		$("#grouperNewBinField").change(function(){
			          			var val = $("#grouperNewBinField option:selected").val();
			          			console.log('grouper field selected',val);

								doc.createObject({
								  qInfo: {
								    qType: 'my-list-object',
								  },
								  qListObjectDef: {
								    qDef: {
								      qFieldDefs: [val],
								      "qSortCriterias": [
							            {
							              "qSortByState": 1,
							              "qSortByFrequency": 0,
							              "qSortByNumeric": 0,
							              "qSortByAscii": 1,
							              "qSortByLoadOrder": 0,
							              "qSortByExpression": 0,
							              "qExpression": {
							                "qv": ""
							              }
							            }
							          ]
								    },
								    qShowAlternatives: true,
								    qInitialDataFetch: [{
								      qTop: 0,
								      qHeight: 1000,
								      qLeft: 0,
								      qWidth: 1,
								    }],
								  },
								})
								.then((listObject) => {
									mListObject = listObject;
									listObject.getLayout()
									.then((layout) => {
								        console.log('Generic object info:', JSON.stringify(layout.qInfo, null, '  '));
								        console.log('List object state:', JSON.stringify(layout.qListObject.qDimensionInfo.qStateCounts, null, '  '));
								        console.log('List object data:', JSON.stringify(layout.qListObject.qDataPages[0].qMatrix, null, '  '));

						          		var listbox = "<div id='grouperBinFieldValues' style='overflow: auto; width: 100%'>";
						          		listbox += "<div style='width:50%; display: inline; float: left;'>";
						          		listbox += "<ol id='grouperBinSelect' class='connectedSortable'>";
										listbox += "<li class='ui-state-disabled'>" + $("#grouperNewBinField").find(":selected").text() + "</li>";
										layout.qListObject.qDataPages[0].qMatrix.forEach( function ( row ) {
											listbox += '<li class="data state' + row[0].qState + ' ui-widget-content" data-value="' + row[0].qElemNumber + '">' + row[0].qText;
											listbox += '</li>';
										} );
										listbox += "</ol>";

										listbox += "<label class='lui-checkbox' style='display: inline; float: left; padding: 5px;'>";
										listbox += "<input class='lui-checkbox__input' type='checkbox' name='addOthers' aria-label='addOthers' />";
										listbox += "<div class='lui-checkbox__check-wrap'>";
										listbox += "<span class='lui-checkbox__check'></span>";
										listbox += "<span class='lui-checkbox__check-text'>include others</span>";
										listbox += "</div>";
										listbox += "</label>";

										listbox += "<button class='lui-button' id='createNewBin'>";
										listbox += "<span class='lui-button__icon  lui-icon  lui-icon--plus'></span><span class='lui-button__text'>create master dimension</span>";
										listbox += "</button>";

										listbox += "</div>";

						          		listbox += "<div id='bins' style='width:50%; display: inline; float: right;'>";

						          		var groupBin = "<ol class='grouperBins connectedSortable'>";
										groupBin += "<li class='ui-state-disabled'>";
										groupBin += "<div style='display: table; width: 100%;'>"
										groupBin += "<input type='text' value='New Bin' style='display: inline-block; width: calc(100% - 48px);'>";
										groupBin += "<button class='lui-button removeGroupBin' style='display: inline-block; width: auto;'><span class='lui-button__icon  lui-icon  lui-icon--close'></span></button>";
										groupBin += "</div></li>";
										groupBin += "</ol>";
						          		listbox += groupBin;

										listbox += "</div>";

										listbox += "<button class='lui-button' id='addNewGroupBin'>";
										listbox += "<span class='lui-button__icon  lui-icon  lui-icon--plus'></span><span class='lui-button__text'>add another bin</span>";
										listbox += "</button>";

										listbox += "</div>";

						          		if($("#grouperBinFieldValues").length)
						          			$("#grouperBinFieldValues").replaceWith(listbox);
						          		else
						          			$("#grouperTextBin").append(listbox);

									    mListObject.on('changed', () => {
									    	mListObject.getLayout().then(layout => {
									    		console.log("changed mListObject", JSON.stringify(layout, null, '  '));

												layout.qListObject.qDataPages[0].qMatrix.forEach( function ( row ) {
													// console.log($("#grouperBinSelect li").filter(function() { return this.innerHTML === row[0].qText; }));
										    		$("li").filter(function() { console.log(this.innerText); return this.innerText === row[0].qText; })
														.removeClass("stateO stateA stateS stateX stateXS")
														.addClass("state"+row[0].qState);
												});
									    	});
									    });

										$("#addNewGroupBin").click(function() {
											$("#bins").append(groupBin);

							          		$( "#grouperBinSelect, .grouperBins" ).sortable({
							          			items: "li:not(.ui-state-disabled)",
										    	connectWith: ".connectedSortable"
										    }).disableSelection();

											$(".removeGroupBin").click(function() {
												console.log(this);
												if($("#bins").children().length > 1){
													$(this).parent().parent().parent().remove();
												}
											});
										});

										$(".removeGroupBin").click(function() {
											console.log(this);
											if($("#bins").children().length > 1){
												$(this).parent().parent().parent().remove();
											}
										});

						          		$( "#grouperBinSelect, .grouperBins" ).sortable({
						          			items: "li:not(.ui-state-disabled)",
									    	connectWith: ".connectedSortable"
									    }).disableSelection();

								    	var selections = [];
						          		$("#createNewBin").click(function(){

									        $(".grouperBins").each(function(i) {
									        	var ol = this;
							          			var sField = {};
										        $(ol).find("input").each(function() {
										        	console.log($(this).val());
										        	sField.name = $(this).val();
										        	selections.push(sField);
									        	});
									        	sVals = [];
										        $(ol).find(".data").each(function() {
										        	console.log($(this).text());
										        	sVals.push($(this).text());
										        	selections[i].vals = sVals;
									        	});
									        });
								    		console.log(JSON.stringify(selections, null, '  '))

										    for(i=0; i<selections.length;i++){
												if(!selections[i].hasOwnProperty("vals")){
													console.log("NO SELECTIONS");
													var error = "Please put at least 1 value in each bin";
													var toast = "<div class='lui-toast' id='grouperToast'><span>" + error + "</span></div>"
													$("#createNewBin").prepend(toast);
													$("#grouperToast").fadeOut(4000);
													setTimeout(function(){$("#grouperToast").remove();},4000);
													return;
												}
											}

											var dimDef = {
										      "qInfo": {
										        "qType": "dimension"
										      },
										      "qDim": {
										        "title": "",
										        "qGrouping": "N",
										        "qFieldDefs": [],
										        "qFieldLabels": []
										      },
										      "qMetaDef": {
										        "title": "",
										        "description": "",
										        "tags": []
										      }
										    };
									    	var ifStmt = "=";
									    	var ctr = 0;
										    for(i=0; i<selections.length;i++){
											    for(j=0; j<selections[i].vals.length;j++){
											    	ifStmt += "if(\"" + val + "\" = '" + selections[i].vals[j] + "', '" + selections[i].name + "'";
											    	if(j<selections[i].vals.length-1){
											    		ifStmt += ",\n";
											    	}
											    	ctr++;
											    }
										    	if(i<selections.length-1){
										    		ifStmt += ",\n";
										    	}
											}
											if($('input[name="addOthers"]').is(':checked'))
												ifStmt += "," + val;
										    for(k=0; k<ctr; k++)
										    	ifStmt += ")";

									    	dimDef.qDim.qFieldDefs.push(ifStmt);
									    	dimDef.qDim.qFieldLabels.push("Binned " + val);
									    	dimDef.qDim.title = "Binned " + val;
									    	dimDef.qMetaDef.title = "Binned " + val;

									    	console.log("dimDef",dimDef);

											doc.createDimension(dimDef)
										    .then(result => {
										    	console.log(result);
										    	if(result.delta){
										    		$("#grouperTextBin").children().slice(2).remove();

													var msg = "Your new master dimension has been added";
													var toast = "<div class='lui-toast' id='grouperToast'><span>" + msg + "</span></div>"
													$("#addNewBin").append(toast);
													$("#grouperToast").fadeOut(4000);
													setTimeout(function(){$("#grouperToast").remove();},4000);
										    	}
										    })
						          		});

								    });
								})
			          		});
			          	})
					})
				}).catch(function(err) {
					console.log('Something went wrong', err);
				});
			});

		}
	};

} );

